_wandb:
    value:
        cli_version: 0.19.8
        m:
            - "1": batch_size
              "6":
                - 3
              "7": []
            - "1": throughput
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 55
                - 63
            "3":
                - 7
                - 13
                - 14
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.16
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 4096
dataset:
    value: cifar10
epochs:
    value: 5
image_size:
    value: 70
learning_rate:
    value: 0.0003
optimizer:
    value: adamw
